# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/emari/Desktop/mbv-axi-slave-ip-repo/vivado-axi-7seg/vivado-axi-7seg.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_0/design_1_rst_clk_wiz_0_100M_0.xci
# IP: The module: 'design_1_rst_clk_wiz_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/emari/Desktop/mbv-axi-slave-ip-repo/vivado-axi-7seg/vivado-axi-7seg.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_0/design_1_rst_clk_wiz_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/emari/Desktop/mbv-axi-slave-ip-repo/vivado-axi-7seg/vivado-axi-7seg.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_0/design_1_rst_clk_wiz_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/emari/Desktop/mbv-axi-slave-ip-repo/vivado-axi-7seg/vivado-axi-7seg.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_0/design_1_rst_clk_wiz_0_100M_0.xci
# IP: The module: 'design_1_rst_clk_wiz_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/emari/Desktop/mbv-axi-slave-ip-repo/vivado-axi-7seg/vivado-axi-7seg.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_0/design_1_rst_clk_wiz_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/emari/Desktop/mbv-axi-slave-ip-repo/vivado-axi-7seg/vivado-axi-7seg.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_0/design_1_rst_clk_wiz_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
