domain_path: C:\Users\emari\Desktop\mbv-axi-slave-ip-repo\vitis-axi-7seg\platform\export\platform\sw\standalone_microblaze_riscv_0
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
